# This is the main configuration file of your Dancer app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "vpex_server"

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# when the charset is set to UTF-8 Dancer will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

session: YAML
session_dir: /tmp/dancer-sessions-vpex
behind_proxy: 1


template: "template_toolkit"
engines:
 template:
   template_toolkit:
     encoding:  'utf8'
     start_tag: '<%'
     end_tag:   '%>'

#logger: console
logger: file
log: debug

log_handler:
    file:
      filename: debug.log
      maxlevel: debug
      minlevel: warning
    screen:
      log_to: "STDERR"
      maxlevel: debug
      minlevel: warning

